import type { AuditFix, AuditReport } from "./audit-types";
import { gradeFor } from "./audit-types";
import { buildFullRepairBrief } from "./agent-prompt";

function groupByPriority(
  fixes: AuditFix[]
): Array<{ priority: string; items: AuditFix[]; note: string }> {
  const notes: Record<string, string> = {
    P0: "Do today - blocking AI readability or visibility.",
    P1: "Do this week - meaningful ranking or snippet gains.",
    P2: "Opportunistic - compounds once P0/P1 are done.",
  };
  return ["P0", "P1", "P2"]
    .map((p) => ({
      priority: p,
      items: fixes.filter((f) => f.priority === p),
      note: notes[p],
    }))
    .filter((g) => g.items.length > 0);
}

/** Plain-text Markdown version of the audit for copy/export. */
export function buildAuditMarkdown(r: AuditReport): string {
  const grade = r.score.grade ?? gradeFor(r.score.total);
  const lines: string[] = [];
  lines.push(`# SiteScore audit - ${r.input.finalUrl || r.input.url}`);
  lines.push("");
  lines.push(`- Audited URL: ${r.input.url}`);
  lines.push(
    `- Final URL: ${r.input.finalUrl}${r.fetch.redirected ? " (redirected)" : ""}`
  );
  lines.push(
    `- Target query: "${r.input.query}" (source: ${r.input.querySource})`
  );
  lines.push(`- Fetched at: ${r.input.fetchedAt} (live fetch, ttl=0)`);
  lines.push(
    `- Score: ${r.score.total}/100 (grade ${grade}) - readability ${r.score.readability}, visibility ${r.score.visibility}, technical ${r.score.technical}`
  );
  lines.push(
    `- Fetch: ${r.fetch.wordCount} words in ${r.fetch.latencyMs}ms; indexed: ${
      r.search.indexation.indexed ? "yes" : "no"
    }; rank: ${r.search.ranking.rank ?? "unranked"}`
  );
  lines.push("");
  lines.push("## Readability → visibility");
  lines.push("");
  lines.push(r.connection.summary);
  lines.push("");
  lines.push(r.connection.correlation);
  lines.push("");
  lines.push("## Fixes (same-day actions)");
  for (const group of groupByPriority(r.fixes)) {
    lines.push("");
    lines.push(`### ${group.priority} - ${group.note}`);
    for (const fix of group.items) {
      lines.push("");
      lines.push(`#### [${fix.priority}] ${fix.title}`);
      lines.push("");
      lines.push(`Why: ${fix.why}`);
      lines.push("");
      lines.push(`How: ${fix.how}`);
      if (fix.codeBefore) {
        lines.push("");
        lines.push("Before:");
        lines.push("```html");
        lines.push(fix.codeBefore);
        lines.push("```");
      }
      if (fix.codeAfter) {
        lines.push("");
        lines.push("After:");
        lines.push("```html");
        lines.push(fix.codeAfter);
        lines.push("```");
      }
    }
  }
  lines.push("");
  lines.push("## Checks");
  lines.push("");
  for (const category of ["readability", "visibility", "technical"] as const) {
    lines.push(`### ${category}`);
    lines.push("");
    for (const c of r.checks.filter((x) => x.category === category)) {
      lines.push(`- [${c.status.toUpperCase()}] ${c.label} - ${c.detail}`);
      lines.push(`  Evidence: ${c.evidence}`);
    }
    lines.push("");
  }
  lines.push("## Visibility detail");
  lines.push("");
  lines.push(`- Indexation probe: \`${r.search.indexation.query}\` → ${
    r.search.indexation.indexed
      ? `indexed (${r.search.indexation.matchUrl ?? "match"})`
      : "not found"
  }`);
  lines.push(
    `- Ranking probe: \`${r.search.ranking.query}\` → ${
      r.search.ranking.rank ?? "unranked"
    } (${r.search.ranking.totalResults} results observed)`
  );
  if (r.search.competitors.length > 0) {
    lines.push("- Competitors:");
    for (const c of r.search.competitors) {
      lines.push(`  - #${c.position ?? "?"} ${c.title} - ${c.url}`);
    }
  }
  lines.push("");
  lines.push(
    `_Generated by SiteScore from a live TinyFish fetch (ttl=0) plus TinyFish search. Rule-based scoring; no generic tips - every finding cites a measured value._`
  );
  lines.push("");
  return lines.join("\n");
}

/** Copy-paste repair brief: every fix as a self-contained agent prompt, P0 first. */
export function buildRepairBriefMarkdown(r: AuditReport): string {
  return buildFullRepairBrief(r.fixes, {
    url: r.input.url,
    finalUrl: r.input.finalUrl,
    query: r.input.query,
  });
}
